const Projects = [
  {
    id: 1,
    name: "Villa Projeleri",
    slug: "Villa",
    description: "Villa açıklaması",
    images: [
      "/images/villa/v1.jpg",
      "/images/villa/v2.jpg",
      "/images/villa/v3.jpg",
      "/images/villa/v4.jpg",
      "/images/villa/v5.jpg",
      "/images/villa/v6.jpg",
      "/images/villa/v7.jpg",
    ],
  },
  {
    id: 2,
    name: "Villa Projeleri",
    slug: "Villa",
    description: "Villa açıklaması",
    images: [
      "/images/villa/v2-1.jpg",
      "/images/villa/v2-2.jpg",
      "/images/villa/v2-3.jpg",
      "/images/villa/v2-4.jpg",
      "/images/villa/v2-5.jpg",
      "/images/villa/v2-6.jpg",
      "/images/villa/v2-7.jpg",
      "/images/villa/v2-8.jpg",
      "/images/villa/v2-9.jpg",
      "/images/villa/v2-10.jpg",
      "/images/villa/v2-11.jpg",
      "/images/villa/v2-12.jpg",
      "/images/villa/v2-13.jpg",
      "/images/villa/v2-14.jpg",
    ],
  },
  {
    id: 3,
    name: "Villa Projeleri",
    slug: "Villa",
    description: "Villa açıklaması",
    images: [
      "/images/villa/v3-1.jpg",
      "/images/villa/v3-2.jpg",
      "/images/villa/v3-3.jpg",
      "/images/villa/v3-4.jpg",
      "/images/villa/v3-5.jpg",
      "/images/villa/v3-6.jpg",
      "/images/villa/v3-7.jpg",
      "/images/villa/v3-8.jpg",
      "/images/villa/v3-9.jpg",
      "/images/villa/v3-10.jpg",
      "/images/villa/v3-11.jpg",
    ],
  },
  {
    id: 4,
    name: "Villa Projeleri",
    slug: "Villa",
    description: "Villa açıklaması",
    images: [
      "/images/villa/v4-1.jpg",
      "/images/villa/v4-2.jpg",
      "/images/villa/v4-3.jpg",
      "/images/villa/v4-4.jpg",
      "/images/villa/v4-5.jpg",
    ],
  },
  {
    id: 5,
    name: "Otel Projeleri",
    slug: "Beyaz Otel Gerze",
    description: "Otel açıklaması",
    images: [
      "/images/hotel/o1.jpg",
      "/images/hotel/o2.jpg",
      "/images/hotel/o3.jpg",
      "/images/hotel/o4.jpg",
      "/images/hotel/o5.jpg",
    ],
  },
  {
    id: 6,
    name: "Fabrika Projeleri",
    slug: "Fabrika ",
    description: "Fabrika açıklaması",
    images: [
      "/images/factory/f1.jpg",
      "/images/factory/f2.jpg",
      "/images/factory/f3.jpg",
      "/images/factory/f4.jpg",
      "/images/factory/f5.jpg",
      "/images/factory/f6.jpg",
      "/images/factory/f7.jpg",
      "/images/factory/f8.jpg",
      "/images/factory/f9.jpg",
    ],
  },
  {
    id: 7,
    name: "Konut Projeleri",
    slug: "Konut",
    description: "Konut açıklaması",
    images: [
      "/images/Konut/k1.jpg",
      "/images/Konut/k2.jpg",
      "/images/Konut/k3.jpg",
      "/images/Konut/k4.jpg",
      "/images/Konut/k5.jpg",
      "/images/Konut/k6.jpg",
    ],
  },
  {
    id: 8,
    name: "Konut Projeleri",
    slug: "Konut",
    description: "Konut açıklaması",
    images: [
      "/images/Konut/k4-1.jpg",
      "/images/Konut/k4-2.jpg",
      "/images/Konut/k4-3.jpg",
      "/images/Konut/k4-4.jpg",
      "/images/Konut/k4-5.jpg",
      "/images/Konut/k4-6.jpg",
    ],
  },
  {
    id: 9,
    name: "Konut Projeleri",
    slug: "Konut",
    description: "Konut açıklaması",
    images: [
      "/images/Konut/k3-1.jpg",
      "/images/Konut/k3-2.jpg",
      "/images/Konut/k3-3.jpg",
      "/images/Konut/k3-4.jpg",
      "/images/Konut/k3-5.jpg",
    ],
  },
  {
    id: 10,
    name: "Konut Projeleri",
    slug: "Konut",
    description: "Konut açıklaması",
    images: [
      "/images/Konut/k2-1.jpg",
      "/images/Konut/k2-2.jpg",
      "/images/Konut/k2-3.jpg",
      "/images/Konut/k2-4.jpg",
      "/images/Konut/k2-5.jpg",
      "/images/Konut/k2-6.jpg",
      "/images/Konut/k2-7.jpg",
      "/images/Konut/k2-8.jpg",
    ],
  },
  {
    id: 11,
    name: "Bungalov Projeleri",
    slug: "Bungalov",
    description: "Konut açıklaması",
    images: [
      "/images/bungalov/b1.jpg",
      "/images/bungalov/b2.jpg",
      "/images/bungalov/b3.jpg",
      "/images/bungalov/b4.jpg",
      "/images/bungalov/b5.jpg",
    ],
  },
  {
    id: 12,
    name: "Bungalov Projeleri",
    slug: "Bungalov",
    description: "Konut açıklaması",
    images: [
      "/images/bungalov/b2-2.jpg",
      "/images/bungalov/b2-1.jpg",
      "/images/bungalov/b2-3.jpg",
      "/images/bungalov/b2-4.jpg",
      "/images/bungalov/b2-5.jpg",
    ],
  },
];

export default Projects;
